{
 "title": "Trinity Weather database Dashboard",
 "time": { "from": "now-6h", "to": "now+2h" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "label": "Meas",
    "query": "SHOW MEASUREMENTS ORDER BY time DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Relative Wind Speed",
   "type": "timeseries",
   "description": "wind speed and/or direction, uncorrected, but relative to the north marker, which\nmay not be facing north\nsee pages 132-135 and ",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT distinct(\"AverageRelativeWindSpeed\") FROM \"autogen\"./^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AverageRelativeWindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Value RWS",
   "type": "gauge",
   "description": "Provides the last Relative wind speed from the panel to the left",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"AverageRelativeWindSpeed\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "AverageRelativeWindDirection" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Gust Speed",
   "type": "timeseries",
   "description": "Get the wind gust from between the sensors on the weather station. See page 132",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT distinct(\"AverageRelativeWindSpeed\") FROM \"autogen\"./^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RelativeGustSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Value RGS",
   "type": "gauge",
   "description": "Gets the Last wind gust from the panel to the left",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"RelativeGustSpeed\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "AverageRelativeWindDirection" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Corrected Average Relative Wind Direction",
   "type": "timeseries",
   "description": "Corrected Wind Direction shall be computed as the Apparent Wind Direction (i.e.: using Compass Heading)\nwhen Compass Heading is available but any one (or more) of GPS Speed and GPS Heading are unavailable. Corrected Wind Direction shall not be computed when Compass Heading is unavailable.\nSee Page 133 ",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT distinct(\"AverageCorrectedWindDirection\") FROM \"autogen\"./^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AverageRelativeWindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Value ACWD",
   "type": "gauge",
   "description": "Gets the last value of the panel to the left",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"AverageCorrectedWindDirection\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "AverageRelativeWindDirection" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Gust Direction",
   "type": "timeseries",
   "description": "Get the relative gust direction over the weather station",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT distinct(\"AverageRelativeWindSpeed\") FROM \"autogen\"./^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RelativeGustDirection" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Value RGD",
   "type": "gauge",
   "description": "Get the last value of the panel to the left",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"RelativeGustDirection\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "AverageRelativeWindDirection" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tempature",
   "type": "stat",
   "description": "Current Temperature at the weather station. see page 137",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "20230316",
     "query": "SELECT last(\"Temperature\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "stat",
   "description": "Dew point at the station. see page 137",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"Dewpoint\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "description": "The relative humidity at the the station.\nRelative Humidity also output, expressed as a percent, measures the current absolute humidity\nrelative to the maximum for that temperature. see page 137",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"Relative_Humidity\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Absolute Humidity",
   "type": "stat",
   "description": "The absolute humidity of the air at the station. \nAbs. Humidity - The humidity of the atmosphere, usually expressed as the number of grams of water contained in 1 cubicmetre of ai. see page 137",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"Absolute_Humidity\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Pressure at Station",
   "type": "stat",
   "description": "Exact pressure at the station not sea level. see page 136\n",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"Pressure_at_Station\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Twilight Astronomical",
   "type": "stat",
   "description": "Begins in the morning, or ends in the evening, when the geometric centre of the Sun is 18 degrees below\nthe horizon. \nsee page 142",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"Twilight(Astronomical)\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "stat",
   "description": "What time sunrise is ",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"SunRiseTime\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Sensor Status",
   "type": "stat",
   "description": "If it's not zero see page 130 of the manual\n",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"WindSensorStatus\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Status",
   "type": "stat",
   "description": "If it's not zero see page 130 of the manual\n",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"Status\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}