{
 "title": "Trinity State Messages Dashboard",
 "description": "Displays statemessages from the CTCPU during observations to check the health of the camera",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "High Voltage Switch",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MUSIC_Power",
     "query": "SELECT first(\"13\") AS \"SIAB 12\" , first(\"14\") AS \"SIAB 13\" , first(\"15\") AS \"SIAB 14\" , first(\"16\") AS \"SIAB 15\" ,first(\"9\") AS \"SIAB 8\" , first(\"10\") AS \"SIAB 9\" , first(\"11\") AS \"SIAB 10\" , first(\"12\") AS \"SIAB 11\" ,first(\"5\") AS \"SIAB 4\" , first(\"6\") AS \"SIAB 5\" , first(\"7\") AS \"SIAB 6\" , first(\"8\") AS \"SIAB 7\" , first(\"1\") AS \"SIAB 0\",first(\"2\") AS \"SIAB 1\" , first(\"3\") AS \"SIAB 2\" , first(\"4\") AS \"SIAB 3\"  FROM \"HV_Status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HV Current 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV_currents",
     "select": [
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HV Current 4",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV_currents",
     "select": [
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last State Message Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TriggerRate",
     "query": "SELECT last(\"value1\") FROM \"TriggerRate\" WHERE time > now() -5m\n",
     "select": [
      [
       { "params": [ "value1" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SIAB Currents",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MUSIC_Power",
     "query": "SELECT first(\"13\") AS \"SIAB 12\" , first(\"14\") AS \"SIAB 13\" , first(\"15\") AS \"SIAB 14\" , first(\"16\") AS \"SIAB 15\" ,first(\"9\") AS \"SIAB 8\" , first(\"10\") AS \"SIAB 9\" , first(\"11\") AS \"SIAB 10\" , first(\"12\") AS \"SIAB 11\" ,first(\"5\") AS \"SIAB 4\" , first(\"6\") AS \"SIAB 5\" , first(\"7\") AS \"SIAB 6\" , first(\"8\") AS \"SIAB 7\" , first(\"1\") AS \"SIAB 0\",first(\"2\") AS \"SIAB 1\" , first(\"3\") AS \"SIAB 2\" , first(\"4\") AS \"SIAB 3\" FROM \"SIABcurrent\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Module Status",
   "type": "stat",
   "description": "add for other channels first(\"5\"), first(\"6\"), first(\"7\"), first(\"8\")",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MUSIC_Power",
     "query": "SELECT first(\"1\") AS L ,first(\"2\") AS C, first(\"3\") AS T, first(\"4\") AS S FROM \"Modules_Status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ASAD Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ASADCurrent",
     "select": [
      [
       { "params": [ "value1" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trigger Board Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TBCurrent",
     "select": [
      [
       { "params": [ "value1" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HV Current 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV_currents",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HV Current 3",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV_currents",
     "select": [
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Triggered Events",
   "type": "stat",
   "description": "number of triggered event in prior two minute recording",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "evt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TriggerRate",
     "select": [
      [
       { "params": [ "value1" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Voltage 2",
   "type": "stat",
   "description": "Actual Channel High Voltage 2",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV",
     "select": [
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Voltage 3",
   "type": "stat",
   "description": "Actual Channel High Voltage 4",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV",
     "select": [
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UC Tempatures",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MUSIC_Power",
     "query": "SELECT first(\"13\") AS \"SIAB 12\" , first(\"14\") AS \"SIAB 13\" , first(\"15\") AS \"SIAB 14\" , first(\"16\") AS \"SIAB 15\" ,first(\"9\") AS \"SIAB 8\" , first(\"10\") AS \"SIAB 9\" , first(\"11\") AS \"SIAB 10\" , first(\"12\") AS \"SIAB 11\" ,first(\"5\") AS \"SIAB 4\" , first(\"6\") AS \"SIAB 5\" , first(\"7\") AS \"SIAB 6\" , first(\"8\") AS \"SIAB 7\" , first(\"1\") AS \"SIAB 0\",first(\"2\") AS \"SIAB 1\" , first(\"3\") AS \"SIAB 2\" , first(\"4\") AS \"SIAB 3\"  FROM \"UC_temps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Music Power",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MUSIC_Power",
     "query": "SELECT first(\"13\") AS \"SIAB 12\" , first(\"14\") AS \"SIAB 13\" , first(\"15\") AS \"SIAB 14\" , first(\"16\") AS \"SIAB 15\" ,first(\"9\") AS \"SIAB 8\" , first(\"10\") AS \"SIAB 9\" , first(\"11\") AS \"SIAB 10\" , first(\"12\") AS \"SIAB 11\" ,first(\"5\") AS \"SIAB 4\" , first(\"6\") AS \"SIAB 5\" , first(\"7\") AS \"SIAB 6\" , first(\"8\") AS \"SIAB 7\" , first(\"1\") AS \"SIAB 0\",first(\"2\") AS \"SIAB 1\" , first(\"3\") AS \"SIAB 2\" , first(\"4\") AS \"SIAB 3\"  FROM \"MUSIC_Power\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SiPM Tempatures",
   "type": "stat",
   "description": "This is converted from the numbers commands which working from the right corner up to set layout of 0 in in the left corner",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MUSIC_Power",
     "query": "SELECT first(\"13\") AS \"SIAB 12\" , first(\"14\") AS \"SIAB 13\" , first(\"15\") AS \"SIAB 14\" , first(\"16\") AS \"SIAB 15\" ,first(\"9\") AS \"SIAB 8\" , first(\"10\") AS \"SIAB 9\" , first(\"11\") AS \"SIAB 10\" , first(\"12\") AS \"SIAB 11\" ,first(\"5\") AS \"SIAB 4\" , first(\"6\") AS \"SIAB 5\" , first(\"7\") AS \"SIAB 6\" , first(\"8\") AS \"SIAB 7\" , first(\"1\") AS \"SIAB 0\",first(\"2\") AS \"SIAB 1\" , first(\"3\") AS \"SIAB 2\" , first(\"4\") AS \"SIAB 3\"   FROM \"SiPM_temps\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "3" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ],
      [
       { "params": [ "4" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Voltage 0",
   "type": "stat",
   "description": "Actual channel High Voltage 1",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV",
     "select": [
      [
       { "params": [ "1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "High Voltage 1",
   "type": "stat",
   "description": "Actual Channel High Voltage 3",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HV",
     "select": [
      [
       { "params": [ "2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}