{
 "title": "Trinity Weather Database Observing",
 "description": "To be used during observation to monitor the conditions at the site.",
 "time": { "from": "now-6h", "to": "now+2h" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Measurement",
    "label": "Meas",
    "query": "SHOW MEASUREMENTS ORDER BY time DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Relative Wind Speed",
   "type": "timeseries",
   "description": "wind speed and/or direction, uncorrected, but relative to the north marker, which\nmay not be facing north\nsee pages 132-135 and ",
   "gridPos": { "h": 21, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT distinct(\"AverageRelativeWindSpeed\") FROM \"autogen\"./^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AverageRelativeWindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Value RWS",
   "type": "gauge",
   "description": "Provides the last Relative wind speed from the panel to the left",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"AverageRelativeWindSpeed\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "AverageRelativeWindDirection" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Value ACWD",
   "type": "volkovlabs-echarts-panel",
   "description": "Gets the last value of the panel to the left",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"AverageCorrectedWindDirection\")  FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "AverageRelativeWindDirection" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Humidity ",
   "type": "stat",
   "description": "The relative humidity at the the station.\nRelative Humidity also output, expressed as a percent, measures the current absolute humidity\nrelative to the maximum for that temperature. see page 137",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "20230316",
     "query": "SELECT last(\"Relative_Humidity\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tempature",
   "type": "stat",
   "description": "Current Temperature at the weather station. see page 137",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "20230316",
     "query": "SELECT last(\"Temperature\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "stat",
   "description": "Current dew point at the weather station. see page 137",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "20230316",
     "query": "SELECT last(\"Dewpoint\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Corrected Average Relative Wind Direction",
   "type": "timeseries",
   "description": "Corrected Wind Direction shall be computed as the Apparent Wind Direction (i.e.: using Compass Heading)\nwhen Compass Heading is available but any one (or more) of GPS Speed and GPS Heading are unavailable. Corrected Wind Direction shall not be computed when Compass Heading is unavailable.\nSee Page 133 ",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT distinct(\"AverageCorrectedWindDirection\") FROM \"autogen\"./^$Measurement$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "AverageRelativeWindSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Status",
   "type": "stat",
   "description": "If it's not zero see page 130 of the manual\n",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT last(\"Status\") FROM /^$Measurement$/ WHERE $timeFilter ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Status",
   "type": "state-timeline",
   "description": "If it's not zero see page 130 of the manual\n",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT distict(\"Status\") FROM /^$Measurement$/  WHERE $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "WindSensorStatus" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}